# Generated by Django 4.2.7 on 2023-12-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-mobile',)},
        ),
    ]
