# Generated by Django 4.2.7 on 2024-01-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_like_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
    ]
