# Generated by Django 4.2.7 on 2024-01-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_like_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-datetime_created',)},
        ),
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
    ]
