# Generated by Django 4.2.7 on 2024-01-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_comment_options_remove_like_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
