# Generated by Django 4.2.7 on 2024-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_one',
            field=models.ImageField(blank=True, null=True, upload_to='products/img_one'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_three',
            field=models.ImageField(blank=True, null=True, upload_to='products/img_three'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_two',
            field=models.ImageField(blank=True, null=True, upload_to='products/img_two'),
        ),
    ]
