# Generated by Django 4.2.7 on 2024-01-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_question_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
