# Generated by Django 4.2.7 on 2024-01-24 18:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_question_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='colors', to='products.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='counted_views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='products/covers', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_one',
            field=models.ImageField(blank=True, null=True, upload_to='products/img_one', verbose_name='عکس اول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_three',
            field=models.ImageField(blank=True, null=True, upload_to='products/img_three', verbose_name='عکس سوم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_two',
            field=models.ImageField(blank=True, null=True, upload_to='products/img_two', verbose_name='عکس دوم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=products.models.random_number, max_length=8, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_number',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='مسیر یو ار ال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.subproductcategory', verbose_name='دسته بندی فرعی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_date'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='picture',
            field=models.ImageField(upload_to='category_pictures', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='properties',
            field=models.ManyToManyField(to='products.productproperties', verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='مسیر یو ار ال'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productproperties',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='question',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.question', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='question',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='setproductproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='setproductproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productproperties', verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='setproductproperty',
            name='value',
            field=models.CharField(max_length=250, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='subproductcategory',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='دسته بندی اصلی'),
        ),
        migrations.AlterField(
            model_name='subproductcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_children', to='products.subproductcategory', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='subproductcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='مسیر یو ار ال'),
        ),
        migrations.AlterField(
            model_name='subproductcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
