# Generated by Django 4.2.7 on 2024-01-27 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_alter_brand_title_alter_color_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestProductUser',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_product', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('products.product',),
        ),
    ]
